ANALYTICS_3300 - Visitor Events API
reachlocal/api-docs pull request #116
Opened 2021-02-11 14:54 UTC by clarkbremer

2021-02-11 17:11 UTC, brianroth-rl requested changes

2021-02-11 17:11 UTC, brianroth-rl commented on source/includes/_visitor_events.md
> +> Example Response
The response structure changes if grouping by visitor_id is present.  This should be called out.  The example response shows only when grouping is active.

2021-02-11 20:22 UTC, brianroth-rl requested changes

2021-02-11 20:22 UTC, brianroth-rl commented on source/includes/_visitor_events.md
> +|visitor_id[]|Yes|Returns events for the specified visitors|
isn't it visitor_ids not visitor_id?

2021-02-11 20:23 UTC, clarkbremer commented on source/includes/_visitor_events.md
> +|visitor_id[]|Yes|Returns events for the specified visitors|
yes

2021-02-11 20:55 UTC, brianroth-rl submitted a review, later dismissed

2021-02-16 15:29 UTC, brianroth-rl approved these changes

2021-02-16 15:29 UTC, merged